spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/live_score?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: root

  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

external:
  api:
    live_score_url: http://static.cricinfo.com/rss/livescores.xml